apiVersion: v1
kind: ContinuousQuery
name: collective-progress
spec:
  mode: query
  sources:
    subscriptions:
      - id: stepup
        nodes:
          - sourceLabel: step_logs
  query: >
    MATCH (s:step_logs)
    RETURN sum(s.steps) AS total